os:
  - linux
  - osx
language: cpp
env:
  - NODE_VERSION="12.16.0"
matrix:
  fast_finish: true
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm;
  - source /tmp/.nvm/nvm.sh;
  - nvm install $NODE_VERSION;
  - nvm use --delete-prefix $NODE_VERSION;
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="g++-4.8";
    fi
install:
  - npm install
script:
  - npm test
  - npm --loglevel=error i -g prebuild
  - prebuild -t 12.16.0 -r node --upload $env:prebuild_upload
  - prebuild -t 5.0.10 -r electron --upload $env:prebuild_upload
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
